# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0460efce782e945018d88b8b003259709a8271c8dcdebcab143f429eecf26166c8ecab9a1dc7d1ee74bbe4660e0d5f19bf7caacd6d8429553ea05752998f801

test:
  secret_key_base: 31da4de1ed9dd28bd5b5d4dd8521450695a7e335d63031cfe5136bb613075d4a2f74a9fb9affd3ce84e385aca02712bafb2553672b5334be2d8b3dd63daa9905

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
